export const LONG_TEXT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget nisl iaculis, maximus urna in, ullamcorper sem. Fusce ultrices ex porta, fringilla risus pretium, semper ipsum. Phasellus volutpat nulla vel tortor vehicula, quis interdum elit tincidunt. Morbi ut ornare ipsum, ac tempus sapien. Etiam ac tempor ex. Nullam commodo convallis ante non molestie. Suspendisse scelerisque nisl nisi. Duis et efficitur enim, non molestie ipsum. Vestibulum rutrum ut nulla vitae viverra. Fusce consequat erat nec ligula ultricies sagittis. Pellentesque molestie risus nunc, vel congue purus euismod sed. In justo turpis, varius sit amet aliquam in, euismod ac mi. Phasellus mattis lorem ac velit iaculis fermentum.

Morbi pellentesque placerat ante, et viverra enim ornare eget. Phasellus finibus consectetur cursus. Suspendisse a velit quis dolor aliquet aliquam ac vitae lectus. Mauris quis arcu ultrices, auctor leo ut, volutpat eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam quis erat at justo porta dictum quis ac tellus. Cras erat orci, rutrum eget augue efficitur, venenatis tincidunt risus. Aenean id libero eu dolor aliquet scelerisque in sit amet nisi. Donec magna neque, iaculis sed scelerisque nec, egestas ac metus.

Phasellus facilisis nulla quam, vitae faucibus felis consectetur quis. Nunc tortor lorem, ultrices quis dui ut, finibus vulputate felis. Suspendisse volutpat tellus a justo bibendum, id vestibulum erat condimentum. Nullam quis ex sit amet est venenatis sollicitudin eu vitae nibh. Vestibulum efficitur convallis elit, sit amet tincidunt quam cursus id. Aliquam in diam justo. Fusce mollis, ante et lacinia pharetra, sapien felis pretium justo, at luctus arcu libero sit amet lorem.

Nullam non urna facilisis, consectetur mi non, rutrum libero. Vestibulum aliquam ex id cursus varius. Integer mattis convallis ligula, et fringilla augue lacinia eu. Praesent rhoncus turpis vitae lectus volutpat ornare. Donec urna magna, facilisis efficitur blandit eget, feugiat a neque. Mauris aliquet viverra lorem, ut vestibulum nisl. Mauris luctus fringilla posuere. Pellentesque ornare eget dui elementum commodo. Curabitur ac bibendum lectus, pharetra euismod lacus. Sed felis quam, lobortis consectetur aliquet sit amet, consequat id urna.

Nunc tempor commodo velit ut ornare. Pellentesque ac lectus sit amet risus lacinia dictum. Donec libero lectus, posuere sed tempus non, auctor at dolor. Sed bibendum eu nunc ut tristique. In ac tincidunt quam, a malesuada orci. Integer sed sapien elit. Integer interdum ornare elit, quis posuere leo imperdiet suscipit. Nunc nec gravida nibh, nec aliquet sem. Vestibulum malesuada cursus suscipit. Quisque ullamcorper purus et vestibulum pharetra. Vivamus laoreet, ante eu feugiat luctus, sem eros fringilla metus, sit amet porta neque nisl ut nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc a ornare tortor. Phasellus magna erat, semper sit amet sem eu, ultricies iaculis augue. Nullam placerat blandit purus vel pellentesque.

Ut laoreet ante lacus, tempus aliquet sapien volutpat id. Integer auctor dui lacus, non pellentesque neque rutrum nec. Integer sed posuere neque. Curabitur accumsan dui vitae egestas placerat. Vestibulum a faucibus est. Donec ac molestie urna. Ut semper tortor et ex tempus, quis ultricies ex viverra. Vivamus in dolor a erat viverra tincidunt. Integer turpis eros, rutrum at finibus ut, commodo quis purus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

In ac est arcu. Proin malesuada molestie metus vitae cursus. Aliquam ut vehicula lectus, vel congue lacus. In finibus tempor rutrum. Nam dapibus urna velit, at aliquet tellus lacinia consequat. Suspendisse facilisis ullamcorper lobortis. Pellentesque commodo, nibh in pharetra faucibus, nibh est volutpat ante, laoreet tristique odio enim ac tellus. Aliquam erat volutpat. Nullam iaculis nisi ut enim auctor, vestibulum tincidunt eros fermentum. Sed tempus, orci faucibus dictum auctor, massa turpis finibus lorem, eu tincidunt risus nulla id purus. Cras ultricies arcu at erat ultricies tempus.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean tincidunt id leo in fringilla. Nam elementum fringilla nisi, eu auctor nisi scelerisque pellentesque. Donec molestie sem non nisl vulputate scelerisque. Fusce consectetur nibh nisi, euismod elementum nunc lacinia quis. Curabitur a elementum lorem, nec scelerisque risus. Fusce id posuere elit. Maecenas vel mollis mi, quis blandit turpis. Curabitur sed condimentum ligula. Donec vitae efficitur libero.

Maecenas interdum cursus tortor quis rutrum. Vivamus eu consequat ante. Vestibulum pellentesque tincidunt ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus pulvinar turpis nec malesuada. Donec a sem volutpat lectus porttitor blandit. Nullam imperdiet accumsan enim sed molestie. Praesent est nulla, sagittis et commodo ac, commodo ut mi. Pellentesque placerat eget lectus sit amet fermentum. Aliquam fermentum massa a mi vestibulum ullamcorper. Vivamus sed lectus dui. Praesent sed ipsum hendrerit sapien condimentum molestie. Aliquam malesuada, erat ac semper scelerisque, nulla mi cursus massa, id commodo tortor magna vel ante. In vitae risus massa. Nunc tellus sem, auctor ut lorem vitae, mollis maximus nisl. Vivamus hendrerit luctus varius.

Morbi in justo turpis. Maecenas at consectetur mi. Nullam vehicula risus eu turpis consectetur malesuada. Ut vitae suscipit ex, placerat ullamcorper felis. Nullam ornare mi et dignissim dapibus. Suspendisse vulputate in libero vel suscipit. Phasellus finibus pharetra justo, a egestas ipsum interdum id. Nullam blandit a erat sit amet consequat. Nunc libero mauris, finibus at enim eu, convallis mattis tellus. Mauris nec porttitor nibh, at volutpat est. Phasellus sed neque ac sapien vulputate pretium. Aliquam tortor purus, congue vel consequat id, convallis eu turpis.

Nulla accumsan ipsum vitae enim sodales viverra. Phasellus faucibus commodo dignissim. Morbi lectus enim, accumsan non metus ut, accumsan bibendum ligula. Ut bibendum sagittis elit ut egestas. Sed in orci at magna tristique faucibus sed eget lacus. Nam at tortor in lacus interdum bibendum id faucibus sapien. Vivamus eu eros vulputate, tempus massa ut, elementum nunc. Nunc egestas pulvinar diam, vitae lacinia augue bibendum quis.

Donec feugiat sem at est condimentum, ut dignissim quam lobortis. Nullam sit amet sagittis tortor. Nunc vestibulum ut erat eu aliquam. Sed gravida est id mi consectetur, ut rutrum neque placerat. Morbi elementum accumsan ante. Etiam tempor sapien nec risus feugiat mollis. Sed aliquet pretium efficitur. Etiam et cursus orci, id dictum urna. Donec quis bibendum risus. Etiam finibus magna a consectetur dapibus. Maecenas sed elementum leo. Aliquam id quam lacinia eros dignissim ultricies. Phasellus imperdiet elit eget neque dapibus elementum. Maecenas in dapibus mi, eu finibus sapien. Nam sagittis elementum metus ut placerat. Nullam convallis justo nec felis efficitur, sit amet eleifend risus dapibus.

Nunc vitae congue ipsum, vitae vestibulum lacus. Mauris nec auctor dolor. Proin mattis tortor eget laoreet elementum. Nulla nunc velit, semper eget faucibus nec, aliquam ut nunc. Sed dapibus iaculis orci, non fringilla augue condimentum ultricies. In luctus mollis enim, et tempor diam porta sit amet. Morbi ut pretium justo. Morbi vitae efficitur tellus, eget hendrerit leo. Sed ultricies libero metus, eu euismod velit viverra vel. Nullam eu semper lectus. Morbi cursus metus nec velit volutpat, molestie consectetur leo tristique.

Nulla ultricies sem eu efficitur iaculis. Aenean aliquam tincidunt urna, sit amet convallis felis sodales vel. Vestibulum vel maximus lorem. Morbi et orci laoreet, semper nunc sed, tincidunt diam. Etiam mollis volutpat tortor, non viverra leo vulputate a. Ut pharetra arcu quis fringilla laoreet. Suspendisse at consectetur lectus, eget suscipit nisl. Nullam eget nulla nisi. Praesent ullamcorper risus quis urna ornare, at placerat lorem aliquam.

Sed sapien tortor, finibus quis urna sit amet, tempus fringilla ante. Nullam commodo neque vitae risus tincidunt, scelerisque rutrum ante sagittis. Donec quis odio ultricies, vulputate nulla ac, sodales libero. In placerat malesuada mauris sit amet porta. Nullam vulputate pellentesque nibh, non posuere arcu. Praesent neque dui, eleifend ac iaculis ut, gravida eget sem. Cras venenatis id elit at vulputate. Maecenas nec tempus ligula. Pellentesque eget lacus porta nibh interdum ullamcorper. Sed vel eros vestibulum arcu interdum viverra. Sed mattis massa tortor, ac congue nunc auctor nec. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Nulla rhoncus nulla mauris, viverra dapibus turpis dapibus in. Nam at condimentum leo. Sed tortor eros, pellentesque quis laoreet eu, efficitur consequat sem. Nulla et elit finibus, eleifend orci at, tempor dolor. Praesent eget congue nisl, sed aliquet tortor. In sed magna tincidunt, eleifend enim sed, interdum tellus. Vivamus ultricies venenatis sem id venenatis. Maecenas id lorem auctor, luctus erat eu, molestie ex.

Sed ut scelerisque lorem. Vivamus ornare condimentum nisi sed imperdiet. Cras congue lectus nunc, sodales fringilla mauris gravida nec. Morbi varius elit erat, non bibendum elit hendrerit ac. Phasellus sit amet egestas metus. Aliquam aliquam ipsum in sollicitudin mollis. Cras egestas efficitur vestibulum. Suspendisse eu nibh in metus euismod consectetur suscipit sit amet risus.

Cras interdum orci tortor, nec lacinia augue feugiat ac. Vestibulum eget arcu dapibus nunc facilisis suscipit ac quis nulla. Integer dapibus tempus neque. Donec aliquet ornare ipsum eu consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porttitor nisl eu dolor placerat, id posuere ligula dapibus. Mauris feugiat varius vehicula. Sed pretium, nisl non lacinia finibus, ante sem commodo diam, vitae ullamcorper mauris enim a nibh. Morbi lorem quam, pellentesque ut erat id, tincidunt varius elit. Donec et nisl quis augue bibendum eleifend dapibus vitae sapien. Nam luctus erat sed massa feugiat fringilla. Aenean placerat enim sit amet neque tincidunt, sit amet porta nisi bibendum. Sed lacus leo, fringilla at urna vel, dictum auctor augue. In luctus nisl in quam dapibus maximus.

Maecenas rhoncus eros nisl, quis ornare nunc gravida eget. Donec diam odio, dapibus ac molestie ac, consequat quis enim. Vivamus vel ante eget erat dapibus laoreet sit amet in lorem. Sed vitae tempus elit. Duis felis lectus, tempor id lacus at, tempus gravida lacus. In ac justo dignissim, convallis odio at, ultricies magna. Nulla hendrerit pretium sodales. Sed at nisl vel ex commodo euismod in quis massa. Duis vitae tortor accumsan, posuere libero sed, ultrices neque. Praesent eu fermentum libero, vitae consectetur sem. Fusce laoreet dolor in risus dictum, non convallis mi egestas. Suspendisse vestibulum tellus a suscipit ultrices.

Etiam in nibh eu nulla sagittis venenatis quis non justo. Duis sit amet tortor pulvinar, luctus nibh non, scelerisque lorem. Cras sodales, lacus et aliquet egestas, elit enim suscipit lacus, ut consequat purus nibh sit amet dolor. Maecenas in magna sit amet mi feugiat ornare id in turpis. Nam sollicitudin dignissim venenatis. Aliquam erat volutpat. Etiam posuere, orci sit amet hendrerit lacinia, est quam malesuada mi, congue mollis nulla odio ac tortor.`;
